[package]
name = "ruscv_kernel"
version = "0.1.0"

[profile.release]
lto = true
debug = 1

[[bin]]
name = "kernel"
path = "src/main.rs"

[features]
default   = ["log-error"]
log-error = []
log-warn  = ["log-error"]
log-info  = ["log-warn"]
log-debug = ["log-info"]
log-trace = ["log-debug"]
